databases:
  - name: talenthub-db
    databaseName: talenthub
    user: talenthub
    region: oregon

services:
  - type: web
    name: talenthub-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: talenthub-db
          property: connectionString
      - key: DIRECT_URL
        fromDatabase:
          name: talenthub-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 30d
      - key: CORS_ORIGINS
        value: https://talent-hub-blond.vercel.app
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: UPLOAD_PATH
        value: ./uploads
